### ISSUE TITLE
registry-issue for initial PR

### ISSUE THREAD

**Issue by UberMouse** [renovatebot/app-support#27]
Hi,

Just installed the Github app and I'm not getting an onboarding PR created. Looking at my Renovate dashboard I can see one failed job (id 137500457) with the result `registry-failure`. It's hard to view the log because it contains a few enormous lines (it caused Chrome to hang so I had to cURL the log down locally) but I couldn't glean anything useful or fixable on my end out of it.

**Comment by rarkins** [comment]
This is a little strange. The first one failed due to a parse error and dumped what it was trying to parse, so that's why it's 1MB.

The second one got the following error instead:

```json
{
  "level": 40,
  "err": {
    "name": "RequestError",
    "code": "ECONNRESET",
    "host": "registry.npmjs.org",
    "hostname": "registry.npmjs.org",
    "method": "GET",
    "path": "/@graphql-codegen%2Ftypescript",
    "protocol": "https:",
    "url": "https://registry.npmjs.org/@graphql-codegen%2Ftypescript",
    "gotOptions": {
      "path": "/@graphql-codegen%2Ftypescript",
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "registry.npmjs.org",
      "port": null,
      "hostname": "registry.npmjs.org",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/@graphql-codegen%2Ftypescript",
      "href": "https://registry.npmjs.org/@graphql-codegen%2Ftypescript",
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "authorization": "** redacted **",
        "cache-control": "no-cache",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate"
      },
      "hooks": {
        "beforeError": [],
        "init": [],
        "beforeRequest": [],
        "beforeRedirect": [],
        "beforeRetry": [],
        "afterResponse": []
      },
      "retry": {
        "methods": {},
        "statusCodes": {},
        "errorCodes": {}
      },
      "decompress": true,
      "throwHttpErrors": true,
      "followRedirect": true,
      "stream": false,
      "form": false,
      "json": true,
      "cache": false,
      "useElectronNet": false,
      "method": "GET"
    },
    "message": "read ECONNRESET",
    "stack": "RequestError: read ECONNRESET\n    at ClientRequest.request.once.error (/home/ubuntu/renovateapp/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/home/ubuntu/renovateapp/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)"
  },
  "regUrl": "https://registry.npmjs.org/",
  "depName": "@graphql-codegen/typescript",
  "msg": "npm registry failure",
  "time": "2020-02-03T04:34:53.089Z"
}
```

I don't know if it's just bad luck or not, let's wait for try 3 next hour.

**Comment by UberMouse** [comment]
Great, thanks for looking into it so quickly!

**Comment by UberMouse** [comment]
Still failing with the same error loading https://registry.npmjs.org/@graphql-codegen%2Ftypescript 🤔
I can load it fine in my browser

**Comment by rarkins** [comment]
It hadn't run again yet - onboarding repos are queued up only once per day. I enqueued it manually and it appears to have run fine.

**Comment by UberMouse** [comment]
Thanks :)
